buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
providers = ["...", "elixir"]
aptPkgs = ["..."]
nixPkgs = ["..."]

[variables]
SECRET_KEY_BASE="ADD"
NIXPACKS_ELIXIR_VERSION="1.14"

[phases.build]
cmds = ["echo start build", "...", "echo done build"]

[start]
cmds = ["echo server start", "mix phx.server"]
