buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
providers = ["...", "ruby"]
aptPkgs = ["..."]
nixPkgs = ["...", "python39", "nodejs-slim-14_x"]

[variables]
NODE_VERSION="14"
SECRET_KEY_BASE="ADD"

[phases.build]
cmds = ["echo start build", "...", "bundle exec rake db:create db:migrate", "echo done build"]

[start]
cmds = ["echo server start", "bundle exec puma -p $PORT --environment=production"]
