buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
providers = ["...", "elixir"]
aptPkgs = ["..."]
nixPkgs = ["..."]

[variables]
SECRET_KEY_BASE="ADD"

[phases.build]
cmds = ["echo start build", "...", "mix compile", "mix assets.deploy", "echo done build"]

[start]
cmds = ["echo server start", "mix phx.server"]
