FROM ghcr.io/railwayapp/nixpacks:latest

ENV PATH="$PATH:/usr/local/bin"

# cd "$(dirname "$0")"
# cd ..
# cp -n .env.sample .env  # -n means "no clobber", so it won't overwrite

# cache /nix
VOLUME /nix