services:
  cache:
    image: redis:6.2-alpine
    env_file:
    - environment.env
    command: redis-server --save 20 1 --loglevel warning 

  database-postgres:
    container_name: db-postgres
    env_file:
    - environment.env
    image: postgres:14.4-alpine
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    volumes:
      - .:/workspace:cached
      - nix:/nix
    security_opt:
      - label:disable
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
volumes:
  postgresql-data:
    driver: local
  nix:
    driver: local
  docker:
    driver: local
