FROM ghcr.io/railwayapp/nixpacks:latest

# Install expect
# RUN apt-get install expect -y

# Download the devbox script
#RUN curl -fsSL https://get.jetpack.io/devbox -o devbox

# Automate the installation of devbox using expect
